language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - php: hhvm-stable
    sudo: required
    dist: trusty
    group: edge
  - nightly
  
install: composer install
  
script: phpunit Tests  
